[package]
name = "feb2"
version = "0.2.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.8.7" }
specs = "0.16.1"
specs-derive = "0.4.1"

